services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Prokl\BitrixModelBundle\Services\Facades\ModelElementFacade: ~
  Prokl\BitrixModelBundle\Services\Facades\ModelElementFacadeCached: ~
  Prokl\BitrixModelBundle\Services\Facades\ModelSectionFacade: ~
  Prokl\BitrixModelBundle\Services\Facades\ModelSectionFacadeCached: ~
  Prokl\BitrixModelBundle\Services\Facades\D7ModelFacade: ~
