services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  model_bundle.ciblockelement:
    public: false
    class: CIBlockElement

  model_bundle.ciblocksection:
    public: false
    class: CIBlockSection

  model_bundle.factory.elements:
    public: true
    class: Prokl\BitrixModelBundle\Services\Factories\ModelElementFactory
    arguments: [!tagged_locator { tag: 'iblock.element.model', index_by: 'key' }, '@model_bundle.ciblockelement']

  Prokl\BitrixModelBundle\Services\Factories\ModelElementFactory: '@model_bundle.factory.elements'

  model_bundle.factory.sections:
    public: true
    class: Prokl\BitrixModelBundle\Services\Factories\ModelSectionFactory
    arguments: [!tagged_locator { tag: 'iblock.section.model', index_by: 'key' }, '@CIBlockSection']

  Prokl\BitrixModelBundle\Services\Factories\ModelSectionFactory: '@model_bundle.factory.sections'
